const SUPABASE_URL = 'https://eknutnlxmougnbxbcdin.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbnV0bmx4bW91Z25ieGJjZGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDQyNDMsImV4cCI6MjA3NDgyMDI0M30.exBZq4ndTk8sMioFV-3Ut_VsyGku-orbPEfELYN-SGA';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);